# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
# Block Designs: The module: 'system' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_HWA_func_0_2/system_HWA_func_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_2 || ORIG_REF_NAME==system_HWA_func_0_2}]

# IP: bd/system/ip/system_HWA_func_0_3/system_HWA_func_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_3 || ORIG_REF_NAME==system_HWA_func_0_3}]

# IP: bd/system/ip/system_HWA_func_0_4/system_HWA_func_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_4 || ORIG_REF_NAME==system_HWA_func_0_4}]

# IP: bd/system/ip/system_HWA_func_0_5/system_HWA_func_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_5 || ORIG_REF_NAME==system_HWA_func_0_5}]

# IP: bd/system/ip/system_HWA_func_0_6/system_HWA_func_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_6 || ORIG_REF_NAME==system_HWA_func_0_6}]

# IP: bd/system/ip/system_HWA_func_0_7/system_HWA_func_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_7 || ORIG_REF_NAME==system_HWA_func_0_7}]

# IP: bd/system/ip/system_HWA_func_0_8/system_HWA_func_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_8 || ORIG_REF_NAME==system_HWA_func_0_8}]

# IP: bd/system/ip/system_HWA_func_0_9/system_HWA_func_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_9 || ORIG_REF_NAME==system_HWA_func_0_9}]

# IP: bd/system/ip/system_HWA_func_0_10/system_HWA_func_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_10 || ORIG_REF_NAME==system_HWA_func_0_10}]

# IP: bd/system/ip/system_HWA_func_0_11/system_HWA_func_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_11 || ORIG_REF_NAME==system_HWA_func_0_11}]

# IP: bd/system/ip/system_HWA_func_0_12/system_HWA_func_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_12 || ORIG_REF_NAME==system_HWA_func_0_12}]

# IP: bd/system/ip/system_HWA_func_0_13/system_HWA_func_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_13 || ORIG_REF_NAME==system_HWA_func_0_13}]

# IP: bd/system/ip/system_HWA_func_0_14/system_HWA_func_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_14 || ORIG_REF_NAME==system_HWA_func_0_14}]

# IP: bd/system/ip/system_HWA_func_0_15/system_HWA_func_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_15 || ORIG_REF_NAME==system_HWA_func_0_15}]

# IP: bd/system/ip/system_HWA_func_0_16/system_HWA_func_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_16 || ORIG_REF_NAME==system_HWA_func_0_16}]

# IP: bd/system/ip/system_HWA_func_0_17/system_HWA_func_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HWA_func_0_17 || ORIG_REF_NAME==system_HWA_func_0_17}]

# IP: bd/system/ip/system_processing_system7_0_axi_periph_0/system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==system_processing_system7_0_axi_periph_0}]

# IP: bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_50M_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc

# XDC: bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_50M_0}]

# XDC: bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_50M_0}]

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
