# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths C:/Temp/RC/solution_gcd_all_addr/impl/ip [current_fileset]

add_files C:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/ipshared/xilinx.com/HWA_func_v1_0/586fc491/constraints/HWA_func_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/bd/system/system_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/Temp/RC/IDE/HWA_system/HWA_system.srcs/sources_1/bd/system/system.bd]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Temp/RC/IDE/HWA_system/HWA_system.cache/wt [current_project]
set_property parent.project_dir C:/Temp/RC/IDE/HWA_system [current_project]
catch { write_hwdef -file system.hwdef }
synth_design -top system -part xc7z020clg484-1
write_checkpoint system.dcp
report_utilization -file system_utilization_synth.rpt -pb system_utilization_synth.pb
