// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// hwa_io
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : reserved
// 0x14 : Data signal of x
//        bit 31~0 - x[31:0] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of y
//        bit 31~0 - y[31:0] (Read/Write)
// 0x20 : Control signal of id
//        bit 0  - id_ap_vld (Read/COR)
//        others - reserved
// 0x24 : Data signal of id
//        bit 31~0 - id[31:0] (Read)
// 0x28 : Control signal of out_r
//        bit 0  - out_r_ap_vld (Read/COR)
//        others - reserved
// 0x2c : Data signal of out_r
//        bit 31~0 - out_r[31:0] (Read)
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XHWA_FUNC_HWA_IO_ADDR_AP_CTRL    0x00
#define XHWA_FUNC_HWA_IO_ADDR_GIE        0x04
#define XHWA_FUNC_HWA_IO_ADDR_IER        0x08
#define XHWA_FUNC_HWA_IO_ADDR_ISR        0x0c
#define XHWA_FUNC_HWA_IO_ADDR_X_DATA     0x14
#define XHWA_FUNC_HWA_IO_BITS_X_DATA     32
#define XHWA_FUNC_HWA_IO_ADDR_Y_DATA     0x1c
#define XHWA_FUNC_HWA_IO_BITS_Y_DATA     32
#define XHWA_FUNC_HWA_IO_ADDR_ID_CTRL    0x20
#define XHWA_FUNC_HWA_IO_ADDR_ID_DATA    0x24
#define XHWA_FUNC_HWA_IO_BITS_ID_DATA    32
#define XHWA_FUNC_HWA_IO_ADDR_OUT_R_CTRL 0x28
#define XHWA_FUNC_HWA_IO_ADDR_OUT_R_DATA 0x2c
#define XHWA_FUNC_HWA_IO_BITS_OUT_R_DATA 32

