// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xhwa_func.h"

extern XHwa_func_Config XHwa_func_ConfigTable[];

XHwa_func_Config *XHwa_func_LookupConfig(u16 DeviceId) {
	XHwa_func_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XHWA_FUNC_NUM_INSTANCES; Index++) {
		if (XHwa_func_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XHwa_func_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XHwa_func_Initialize(XHwa_func *InstancePtr, u16 DeviceId) {
	XHwa_func_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XHwa_func_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XHwa_func_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

