// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xhwa_func.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XHwa_func_CfgInitialize(XHwa_func *InstancePtr, XHwa_func_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Hwa_io_BaseAddress = ConfigPtr->Hwa_io_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XHwa_func_Start(XHwa_func *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_AP_CTRL) & 0x80;
    XHwa_func_WriteReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_AP_CTRL, Data | 0x01);
}

u32 XHwa_func_IsDone(XHwa_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XHwa_func_IsIdle(XHwa_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XHwa_func_IsReady(XHwa_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XHwa_func_EnableAutoRestart(XHwa_func *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwa_func_WriteReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_AP_CTRL, 0x80);
}

void XHwa_func_DisableAutoRestart(XHwa_func *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwa_func_WriteReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_AP_CTRL, 0);
}

void XHwa_func_SetX(XHwa_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwa_func_WriteReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_X_DATA, Data);
}

u32 XHwa_func_GetX(XHwa_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_X_DATA);
    return Data;
}

void XHwa_func_SetY(XHwa_func *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwa_func_WriteReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_Y_DATA, Data);
}

u32 XHwa_func_GetY(XHwa_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_Y_DATA);
    return Data;
}

u32 XHwa_func_GetId(XHwa_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_ID_DATA);
    return Data;
}

u32 XHwa_func_GetIdVld(XHwa_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_ID_CTRL);
    return Data & 0x1;
}

u32 XHwa_func_GetOut_r(XHwa_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_OUT_R_DATA);
    return Data;
}

u32 XHwa_func_GetOut_rVld(XHwa_func *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_OUT_R_CTRL);
    return Data & 0x1;
}

void XHwa_func_InterruptGlobalEnable(XHwa_func *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwa_func_WriteReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_GIE, 1);
}

void XHwa_func_InterruptGlobalDisable(XHwa_func *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwa_func_WriteReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_GIE, 0);
}

void XHwa_func_InterruptEnable(XHwa_func *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_IER);
    XHwa_func_WriteReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_IER, Register | Mask);
}

void XHwa_func_InterruptDisable(XHwa_func *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_IER);
    XHwa_func_WriteReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_IER, Register & (~Mask));
}

void XHwa_func_InterruptClear(XHwa_func *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwa_func_WriteReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_ISR, Mask);
}

u32 XHwa_func_InterruptGetEnabled(XHwa_func *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_IER);
}

u32 XHwa_func_InterruptGetStatus(XHwa_func *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHwa_func_ReadReg(InstancePtr->Hwa_io_BaseAddress, XHWA_FUNC_HWA_IO_ADDR_ISR);
}

